version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: personapp-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: persona_db
      MARIADB_USER: persona_db
      MARIADB_PASSWORD: persona_db
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: personapp-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: persona_db
      MONGO_INITDB_ROOT_PASSWORD: persona_db
      MONGO_INITDB_DATABASE: persona_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/persona_ddl_mongo.js:/docker-entrypoint-initdb.d/persona_ddl_mongo.js:ro
      - ./scripts/persona_dml_mongo.js:/docker-entrypoint-initdb.d/persona_dml_mongo.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://persona_db:persona_db@localhost:27017/admin --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  cli-app:
    build:
      context: .
      dockerfile: Dockerfile.cli
    container_name: personapp-cli
    depends_on:
      mariadb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/persona_db
      - SPRING_DATASOURCE_USERNAME=persona_db
      - SPRING_DATASOURCE_PASSWORD=persona_db
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_USERNAME=persona_db
      - SPRING_DATA_MONGODB_PASSWORD=persona_db
    stdin_open: true
    tty: true

  rest-app:
    build:
      context: .
      dockerfile: Dockerfile.rest
    container_name: personapp-rest
    depends_on:
      mariadb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/persona_db
      - SPRING_DATASOURCE_USERNAME=persona_db
      - SPRING_DATASOURCE_PASSWORD=persona_db
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_USERNAME=persona_db
      - SPRING_DATA_MONGODB_PASSWORD=persona_db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  mariadb_data:
  mongodb_data: