FROM maven:3.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean install -B -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/rest-input-adapter/target/rest-input-adapter-*.jar app.jar
RUN mkdir -p /app/logs && chmod 777 /app/logs

ENTRYPOINT ["java", "-jar", "app.jar"]