FROM maven:3.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean install -B -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/*/target/*.jar app.jar
RUN mkdir -p /app/logs && chmod 777 /app/logs

EXPOSE 3000
ENTRYPOINT ["java", "-jar", "app.jar"]